import productsData from "@/data/ProductData.json";
import imageManifest from "@/data/image-manifest.json";

// Generated by `npm run images` (scripts/optimize-images.mjs).
export type ImageAsset = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

const manifest = imageManifest as Record<string, ImageAsset>;

function asset(key: string): ImageAsset {
  const image = manifest[key];
  if (!image) {
    throw new Error(`No optimized image for "${key}". Run \`npm run images\`.`);
  }
  return image;
}

export const categories = [
  "All",
  "Tech",
  "Gaming",
  "Fragrance",
  "Home",
  "Kitchen",
  "Sports",
] as const;

export type Category = (typeof categories)[number];

export type Product = Omit<(typeof productsData)[number], "images" | "category"> & {
  category: Exclude<Category, "All">;
  /** Always two: the main shot and a second view (another photo or a close-up). */
  images: ImageAsset[];
};

export const products: Product[] = productsData.map((product) => ({
  ...product,
  category: product.category as Product["category"],
  images: product.images.map(asset),
}));

export const siteImages = {
  gaming: asset("site:gaming"),
  tech: asset("site:tech"),
  fragrance: asset("site:fragrance"),
  home: asset("site:home"),
  kitchen: asset("site:kitchen"),
  sports: asset("site:sports"),
  banner: asset("site:banner"),
};

export function isCategory(value: string): value is Category {
  return (categories as readonly string[]).includes(value);
}

export function getProduct(id: string | number) {
  const numericId = typeof id === "number" ? id : parseInt(id, 10);
  return products.find((product) => product.id === numericId);
}

export function getProducts(ids: number[]) {
  return ids.flatMap((id) => getProduct(id) ?? []);
}

export function getProductsByCategory(category: Category) {
  return category === "All"
    ? products
    : products.filter((product) => product.category === category);
}

/** The small, serializable slice of a product that client components need. */
export type ProductSummary = Pick<
  Product,
  "id" | "brand" | "title" | "category" | "price" | "images"
>;

export function toSummary(product: Product): ProductSummary {
  return {
    id: product.id,
    brand: product.brand,
    title: product.title,
    category: product.category,
    price: product.price,
    images: product.images,
  };
}

export { formatPrice } from "@/lib/format";
